# Generated by Django 6.0.1 on 2026-01-23 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Armazena o username mesmo se o usuário for deletado', max_length=150, verbose_name='Nome de usuário')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'Visualização'), ('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('ACCESS_DENIED', 'Acesso Negado'), ('ERROR', 'Erro')], max_length=20, verbose_name='Ação')),
                ('description', models.TextField(help_text='Descrição detalhada da ação', verbose_name='Descrição')),
                ('severity', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10, verbose_name='Severidade')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, help_text='Informações do navegador/dispositivo', verbose_name='User Agent')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='URL acessada')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP')),
                ('extra_data', models.JSONField(blank=True, help_text='Informações extras em formato JSON', null=True, verbose_name='Dados adicionais')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_au_timesta_40aa9a_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx')],
            },
        ),
    ]
