# Generated by Django 4.2.7 on 2026-02-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('icone', models.CharField(default='bi-bar-chart-line', help_text='Classe do Bootstrap Icons (ex: bi-bar-chart-line)', max_length=50, verbose_name='Ícone Bootstrap')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria de Painel',
                'verbose_name_plural': 'Categorias de Painéis',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PainelBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Painel')),
                ('descricao', models.TextField(blank=True, help_text='Breve descrição do painel', verbose_name='Descrição')),
                ('iframe_url', models.URLField(blank=True, help_text='Cole aqui a URL de incorporação do Power BI', max_length=2000, verbose_name='URL do iframe (Power BI)')),
                ('icone', models.CharField(default='bi-file-earmark-bar-graph', help_text='Classe do Bootstrap Icons (ex: bi-file-earmark-bar-graph)', max_length=50, verbose_name='Ícone Bootstrap')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paineis', to='accounts.categoriapainel', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Painel BI',
                'verbose_name_plural': 'Painéis BI',
                'ordering': ['categoria__ordem', 'ordem', 'titulo'],
            },
        ),
    ]
