# Generated by Django 4.2.7 on 2026-02-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_categoriapainel_painelbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelbi',
            name='grupo_acesso',
            field=models.ForeignKey(blank=True, help_text='Grupo que pode visualizar este painel. Vazio = visível para todos com acesso à categoria.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paineis_bi', to='auth.group', verbose_name='Grupo de Acesso'),
        ),
    ]
